"""Finetune launch flow (round 29).

Builds a finetune config + a ready-to-run training script from a small set of
UI/chat inputs (base model, dataset path, hyperparameters). The script is plain
PyTorch/HuggingFace so it runs on the workbench Python kernel, reports metrics
via report_metric(...), and tags the dataset so the run is comparable.

The intent layer records a `kind="finetune"` run with this config + code, so the
pipeline view and advisor treat a finetune exactly like any other variant.
"""

from __future__ import annotations

import json
from typing import Any

DEFAULT_HP = {
    "epochs": 3,
    "learning_rate": 2e-5,
    "batch_size": 8,
    "max_length": 512,
    "lora_r": 0,          # 0 = full finetune, >0 = LoRA adapter
    "weight_decay": 0.01,
    "warmup_ratio": 0.1,
    "seed": 42,
}


def normalize_finetune_config(raw: dict | None) -> dict:
    """Merge user-supplied finetune options over safe defaults."""
    cfg = dict(DEFAULT_HP)
    for k, v in (raw or {}).items():
        if v is None:
            continue
        if k in DEFAULT_HP:
            try:
                cfg[k] = int(v) if isinstance(DEFAULT_HP[k], int) else float(v)
            except (TypeError, ValueError):
                pass
        else:
            cfg[k] = v
    cfg.setdefault("base_model", "")
    cfg.setdefault("dataset", "")
    cfg.setdefault("task", "classification")
    cfg.setdefault("output_dir", "finetune-out")
    cfg["base_model"] = str(cfg.get("base_model") or "").strip()
    cfg["dataset"] = str(cfg.get("dataset") or "").strip()
    return cfg


def finetune_config_json(cfg: dict) -> str:
    return json.dumps(cfg, separators=(",", ":"))


def validate_finetune(cfg: dict) -> str:
    """Return an error message, or '' if the finetune setup is launchable."""
    if not cfg.get("base_model"):
        return "A base model is required (e.g. distilbert-base-uncased)."
    if not cfg.get("dataset"):
        return "A training dataset file is required (a path readable by pandas)."
    if cfg.get("epochs", 0) < 1:
        return "epochs must be >= 1."
    if cfg.get("learning_rate", 0) <= 0:
        return "learning_rate must be > 0."
    if cfg.get("lora_r", 0) < 0:
        return "lora_r must be >= 0 (0 = full finetune, >0 = LoRA)."
    return ""


def finetune_script(cfg: dict) -> str:
    """Generate a training script for the given finetune config.

    The script reads `finetune_cfg` from the kernel, imports torch /
    transformers when available (reporting a clear error if not), and reports
    per-epoch metrics via report_metric(...) so the run records them. It is a
    sensible starting point — the agent may edit it before running.
    """
    base = cfg.get("base_model") or "distilbert-base-uncased"
    ds = cfg.get("dataset") or "data.csv"
    epochs = int(cfg.get("epochs") or 3)
    lr = cfg.get("learning_rate") or 2e-5
    bs = int(cfg.get("batch_size") or 8)
    ml = int(cfg.get("max_length") or 512)
    wd = cfg.get("weight_decay") or 0.01
    lora_r = int(cfg.get("lora_r") or 0)
    seed = int(cfg.get("seed") or 42)
    task = cfg.get("task") or "classification"
    out_dir = cfg.get("output_dir") or "finetune-out"

    lora_imports = (
        "from peft import LoraConfig, get_peft_model" if lora_r > 0 else ""
    )
    lora_block = (
        f'''
# LoRA adapter (rank={lora_r})
lora_cfg = LoraConfig(r={lora_r}, lora_alpha={lora_r * 2},
                      task_type="SEQ_CLS")
model = get_peft_model(model, lora_cfg)
print("LoRA trainable params:",
      sum(p.numel() for p in model.parameters() if p.requires_grad))'''
        if lora_r > 0 else ""
    )
    return f'''# Finetune {base} on {ds}  ({task})  — generated by Fox
# Edit this script and rerun via `run_python` (or launch again from the UI).
import os, random
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          TrainingArguments, Trainer)
{lora_imports}

finetune_cfg = {{"base_model": "{base}", "dataset": "{ds}",
    "epochs": {epochs}, "learning_rate": {lr}, "batch_size": {bs},
    "max_length": {ml}, "weight_decay": {wd}, "lora_r": {lora_r},
    "seed": {seed}, "task": "{task}", "output_dir": "{out_dir}"}}

torch.manual_seed({seed}); np.random.seed({seed}); random.seed({seed})
report_dataset("{ds}")

print("Loading", finetune_cfg["dataset"])
df = pd.read_csv(finetune_cfg["dataset"])
print("Rows:", len(df), "| columns:", list(df.columns)[:10])

# Default to a text + label pair; adapt columns to your dataset.
text_col = "text" if "text" in df.columns else df.columns[0]
label_col = "label" if "label" in df.columns else df.columns[1]
train_df, eval_df = df.sample(frac=0.9, random_state={seed}), df.sample(frac=0.1, random_state={seed})

tokenizer = AutoTokenizer.from_pretrained(finetune_cfg["base_model"])
model = AutoModelForSequenceClassification.from_pretrained(
    finetune_cfg["base_model"], num_labels=df[label_col].nunique())
{lora_block}

def _enc(batch):
    return tokenizer(list(batch[text_col]), truncation=True,
                     padding=True, max_length=finetune_cfg["max_length"],
                     return_tensors="pt")

train_ds = _enc(train_df); train_ds["labels"] = torch.tensor(train_df[label_col].values)
eval_ds = _enc(eval_df);   eval_ds["labels"] = torch.tensor(eval_df[label_col].values)

args = TrainingArguments(
    output_dir=finetune_cfg["output_dir"],
    num_train_epochs=finetune_cfg["epochs"],
    learning_rate=finetune_cfg["learning_rate"],
    per_device_train_batch_size=finetune_cfg["batch_size"],
    per_device_eval_batch_size=finetune_cfg["batch_size"],
    weight_decay=finetune_cfg["weight_decay"],
    warmup_ratio=finetune_cfg.get("warmup_ratio", 0.1),
    evaluation_strategy="epoch", save_strategy="epoch",
    seed=finetune_cfg["seed"], logging_steps=10)

trainer = Trainer(model=model, args=args,
                  train_dataset=train_ds, eval_dataset=eval_ds)
trainer.train()
metrics = trainer.evaluate()
report_metric("eval_loss", metrics.get("eval_loss"))
# Report a headline accuracy on the eval split.
logits = trainer.predict(eval_ds).predictions
preds = logits.argmax(-1)
acc = float((preds == eval_ds["labels"]).float().mean())
report_metric("accuracy", acc)
print("Finetune done. Eval accuracy:", acc)
'''


def finetune_summary(cfg: dict) -> str:
    """A short human-readable summary of a finetune launch (chat reply)."""
    lora = f"LoRA r={cfg['lora_r']}" if cfg["lora_r"] else "full finetune"
    return (f"## Finetune launch — {cfg['base_model']} on {cfg['dataset']}\n\n"
            f"- **Setup**: {lora} · {cfg['epochs']} epoch(s) · lr {cfg['learning_rate']:g} "
            f"· batch {cfg['batch_size']} · max_len {cfg['max_length']}\n"
            f"- **Task**: {cfg.get('task')}\n\n"
            f"A ready-to-run training script was generated and attached to this run. "
            f"Ask the agent to run it (or run it yourself with run_python) to "
            f"produce a finetuned checkpoint + eval metrics.")


__all__ = ["normalize_finetune_config", "finetune_config_json",
           "validate_finetune", "finetune_script", "finetune_summary"]
