"""Built-in themes for the Fox TUI.

Original palettes tuned for readability in a dark/light developer terminal.
Every theme carries the full set of semantic tokens; missing tokens fall back
to the opencode-dark defaults.
"""

from __future__ import annotations

from .theme import Theme

# ------------------------------------------------------------------ defaults --

_DARK = {
    "background": "#0b0e14",
    "surface": "#11151f",
    "surfaceAlt": "#151a26",
    "panel": "#10141d",
    "panelInactive": "#0d1119",
    "border": "#232a38",
    "borderActive": "#3b455a",
    "borderMuted": "#1b2230",
    "text": "#e6edf3",
    "textMuted": "#8b94a7",
    "textSubtle": "#5c6577",
    "textInverse": "#0b0e14",
    "textLink": "#7aa2f7",
    "accent": "#7aa2f7",
    "accentHover": "#8fb1ff",
    "accentActive": "#5f8bef",
    "accentMuted": "#2c3d5f",
    "success": "#9ece6a",
    "warning": "#e0af68",
    "error": "#f7768e",
    "info": "#7dcfff",
    "selectionBackground": "#26314a",
    "selectionForeground": "#e6edf3",
    "inputBackground": "#0f1420",
    "inputForeground": "#e6edf3",
    "inputPlaceholder": "#5c6577",
    "inputCursor": "#7aa2f7",
    "sidebarBackground": "#0d1119",
    "sidebarForeground": "#c7d0dd",
    "sidebarSelectedBackground": "#1c2438",
    "sidebarSelectedForeground": "#ffffff",
    "sidebarMuted": "#6b758a",
    "headerBackground": "#0d1119",
    "headerForeground": "#c7d0dd",
    "headerAccent": "#7aa2f7",
    "statusBarBackground": "#10141d",
    "statusBarForeground": "#8b94a7",
    "statusBarError": "#f7768e",
    "statusBarWarning": "#e0af68",
    "statusBarSuccess": "#9ece6a",
    "codeBackground": "#0f1420",
    "codeForeground": "#d5dde9",
    "codeLineNumber": "#4c5568",
    "codeLanguageLabel": "#7aa2f7",
    "diffAddedBackground": "#14291c",
    "diffAddedForeground": "#9ece6a",
    "diffRemovedBackground": "#2d1620",
    "diffRemovedForeground": "#f7768e",
    "diffContextForeground": "#8b94a7",
    "spinner": "#7aa2f7",
    "loadingText": "#8b94a7",
}

_LIGHT = {
    "background": "#f7f8fb",
    "surface": "#ffffff",
    "surfaceAlt": "#eef1f6",
    "panel": "#ffffff",
    "panelInactive": "#f1f3f8",
    "border": "#d7dde8",
    "borderActive": "#a8b3c7",
    "borderMuted": "#e3e8f1",
    "text": "#1f2430",
    "textMuted": "#5c6577",
    "textSubtle": "#8a93a6",
    "textInverse": "#ffffff",
    "textLink": "#2f6feb",
    "accent": "#2f6feb",
    "accentHover": "#4180ff",
    "accentActive": "#2459c7",
    "accentMuted": "#dbe6ff",
    "success": "#2e8555",
    "warning": "#b08800",
    "error": "#d1242f",
    "info": "#0969da",
    "selectionBackground": "#dbe6ff",
    "selectionForeground": "#1f2430",
    "inputBackground": "#ffffff",
    "inputForeground": "#1f2430",
    "inputPlaceholder": "#8a93a6",
    "inputCursor": "#2f6feb",
    "sidebarBackground": "#f1f3f8",
    "sidebarForeground": "#374151",
    "sidebarSelectedBackground": "#dbe6ff",
    "sidebarSelectedForeground": "#111827",
    "sidebarMuted": "#7b8494",
    "headerBackground": "#ffffff",
    "headerForeground": "#374151",
    "headerAccent": "#2f6feb",
    "statusBarBackground": "#f1f3f8",
    "statusBarForeground": "#5c6577",
    "statusBarError": "#d1242f",
    "statusBarWarning": "#b08800",
    "statusBarSuccess": "#2e8555",
    "codeBackground": "#f6f8fa",
    "codeForeground": "#24292f",
    "codeLineNumber": "#8a93a6",
    "codeLanguageLabel": "#2f6feb",
    "diffAddedBackground": "#e6f6ec",
    "diffAddedForeground": "#2e8555",
    "diffRemovedBackground": "#ffebe9",
    "diffRemovedForeground": "#d1242f",
    "diffContextForeground": "#57606a",
    "spinner": "#2f6feb",
    "loadingText": "#5c6577",
}

_MIDNIGHT = {
    **_DARK,
    "background": "#05070c",
    "surface": "#0a0e17",
    "surfaceAlt": "#0e1420",
    "panel": "#090d15",
    "panelInactive": "#070a10",
    "border": "#1c2433",
    "borderActive": "#35507f",
    "borderMuted": "#131a26",
    "text": "#e8edf6",
    "textMuted": "#7d88a0",
    "accent": "#8cb2ff",
    "accentHover": "#a6c4ff",
    "accentActive": "#6d95e8",
    "accentMuted": "#1e2f4d",
    "selectionBackground": "#22314f",
    "inputBackground": "#0b101b",
    "codeBackground": "#0a0f1a",
    "sidebarBackground": "#070a10",
    "sidebarSelectedBackground": "#172239",
    "headerBackground": "#070a10",
    "statusBarBackground": "#090d15",
}

_HIGH_CONTRAST_DARK = {
    **_DARK,
    "background": "#000000",
    "surface": "#0d0d0d",
    "surfaceAlt": "#1a1a1a",
    "panel": "#050505",
    "panelInactive": "#0a0a0a",
    "border": "#555555",
    "borderActive": "#ffffff",
    "borderMuted": "#333333",
    "text": "#ffffff",
    "textMuted": "#c0c0c0",
    "textSubtle": "#9a9a9a",
    "textLink": "#7fd0ff",
    "accent": "#4fa3ff",
    "accentHover": "#6db6ff",
    "accentActive": "#2e86f0",
    "accentMuted": "#1b3a5e",
    "success": "#5aff6b",
    "warning": "#ffd166",
    "error": "#ff5c5c",
    "info": "#6ee7ff",
    "selectionBackground": "#2b5fb8",
    "selectionForeground": "#ffffff",
    "inputBackground": "#000000",
    "inputCursor": "#ffffff",
    "sidebarBackground": "#000000",
    "sidebarSelectedBackground": "#2b5fb8",
    "sidebarSelectedForeground": "#ffffff",
    "sidebarMuted": "#a0a0a0",
    "headerBackground": "#000000",
    "headerAccent": "#7fd0ff",
    "statusBarBackground": "#000000",
    "statusBarForeground": "#c0c0c0",
    "codeBackground": "#0a0a0a",
    "codeLineNumber": "#888888",
    "diffAddedBackground": "#0a2a12",
    "diffRemovedBackground": "#2a0a0a",
    "spinner": "#7fd0ff",
}

_HIGH_CONTRAST_LIGHT = {
    **_LIGHT,
    "background": "#ffffff",
    "surface": "#ffffff",
    "surfaceAlt": "#eef0f4",
    "panel": "#ffffff",
    "panelInactive": "#f5f6f8",
    "border": "#9aa2b1",
    "borderActive": "#1f2430",
    "borderMuted": "#c3c9d4",
    "text": "#000000",
    "textMuted": "#3d4452",
    "textSubtle": "#5c6577",
    "textLink": "#0052cc",
    "accent": "#0052cc",
    "accentHover": "#003d99",
    "accentActive": "#00307a",
    "accentMuted": "#d6e4ff",
    "success": "#007b2e",
    "warning": "#7a5200",
    "error": "#c4000f",
    "info": "#005f8f",
    "selectionBackground": "#a8c8ff",
    "selectionForeground": "#000000",
    "inputBackground": "#ffffff",
    "inputCursor": "#000000",
    "sidebarBackground": "#f5f6f8",
    "sidebarSelectedBackground": "#a8c8ff",
    "sidebarSelectedForeground": "#000000",
    "sidebarMuted": "#6b7484",
    "headerBackground": "#ffffff",
    "headerAccent": "#0052cc",
    "statusBarBackground": "#eef0f4",
    "statusBarForeground": "#3d4452",
    "codeBackground": "#fafbfc",
    "codeLineNumber": "#6b7484",
    "diffAddedBackground": "#d8f2df",
    "diffRemovedBackground": "#ffd9d9",
    "spinner": "#0052cc",
}

_SOLARIZED_DARK = {
    "background": "#002b36",
    "surface": "#073642",
    "surfaceAlt": "#0a404e",
    "panel": "#012b35",
    "panelInactive": "#03222b",
    "border": "#0a3f4c",
    "borderActive": "#268bd2",
    "borderMuted": "#06353f",
    "text": "#839496",
    "textMuted": "#586e75",
    "textSubtle": "#475b62",
    "textInverse": "#002b36",
    "textLink": "#268bd2",
    "accent": "#268bd2",
    "accentHover": "#4fa8dd",
    "accentActive": "#1978b8",
    "accentMuted": "#0e4a66",
    "success": "#859900",
    "warning": "#b58900",
    "error": "#dc322f",
    "info": "#2aa198",
    "selectionBackground": "#0e4a66",
    "selectionForeground": "#eee8d5",
    "inputBackground": "#012b35",
    "inputForeground": "#839496",
    "inputPlaceholder": "#586e75",
    "inputCursor": "#b58900",
    "sidebarBackground": "#00222b",
    "sidebarForeground": "#93a1a1",
    "sidebarSelectedBackground": "#0e4a66",
    "sidebarSelectedForeground": "#eee8d5",
    "sidebarMuted": "#546e75",
    "headerBackground": "#00222b",
    "headerForeground": "#93a1a1",
    "headerAccent": "#268bd2",
    "statusBarBackground": "#012b35",
    "statusBarForeground": "#586e75",
    "statusBarError": "#dc322f",
    "statusBarWarning": "#b58900",
    "statusBarSuccess": "#859900",
    "codeBackground": "#01313d",
    "codeForeground": "#93a1a1",
    "codeLineNumber": "#546e75",
    "codeLanguageLabel": "#268bd2",
    "diffAddedBackground": "#003b16",
    "diffAddedForeground": "#859900",
    "diffRemovedBackground": "#3b0716",
    "diffRemovedForeground": "#dc322f",
    "diffContextForeground": "#586e75",
    "spinner": "#2aa198",
    "loadingText": "#586e75",
}

_BUILTIN = {
    "opencode-dark": ("dark", _DARK),
    "opencode-light": ("light", _LIGHT),
    "opencode-midnight": ("dark", _MIDNIGHT),
    "high-contrast-dark": ("dark", _HIGH_CONTRAST_DARK),
    "high-contrast-light": ("light", _HIGH_CONTRAST_LIGHT),
    "solarized-dark": ("dark", _SOLARIZED_DARK),
}

THEME_ORDER = ["opencode-dark", "opencode-light", "opencode-midnight",
               "solarized-dark", "high-contrast-dark", "high-contrast-light"]


def builtin_names() -> list[str]:
    return list(THEME_ORDER)


def load_theme(name: str) -> Theme:
    """Load a built-in theme by name; falls back to opencode-dark."""
    entry = _BUILTIN.get(name)
    if entry is None:
        entry = _BUILTIN["opencode-dark"]
        name = "opencode-dark"
    type_, colors = entry
    merged = dict(_DARK)
    merged.update(colors)
    return Theme(name=name, type_=type_, colors=merged)
