"""Tool registry: schemas for the LLM + execution functions used by the coordinator.

Every tool execution is recorded in the conversation as a `tool` message so the
workflow is fully auditable. Figures produced by kernels are auto-registered as
artifacts with full provenance (code + environment snapshot).
"""

from __future__ import annotations

import asyncio
import base64
import dataclasses
import json
from typing import Any, Awaitable, Callable

from ..artifacts.store import Artifact, ArtifactStore
from ..kernels.manager import KernelManager
from ..permissions import PermissionManager
from ..store import ProjectStore

ToolFn = Callable[..., Awaitable[str]]


@dataclasses.dataclass
class ToolContext:
    kernels: KernelManager
    artifacts: ArtifactStore
    store: ProjectStore
    permissions: PermissionManager
    approval: "ApprovalBroker | None" = None
    emit: Callable[[str, dict], Awaitable[None]] | None = None


TOOL_SCHEMAS: list[dict] = [
    {
        "type": "function",
        "function": {
            "name": "run_python",
            "description": (
                "Execute Python code in the persistent scientific kernel "
                "(numpy/pandas/scipy/matplotlib). Variables persist between calls. "
                "Figures rendered with matplotlib are automatically saved as artifacts. "
                "Use this for computations, data analysis, and plots."
            ),
            "parameters": {
                "type": "object",
                "properties": {"code": {"type": "string", "description": "Python code to run"}},
                "required": ["code"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_r",
            "description": "Execute R code. Requires Rscript to be installed.",
            "parameters": {
                "type": "object",
                "properties": {"code": {"type": "string", "description": "R code to run"}},
                "required": ["code"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_shell",
            "description": (
                "Run a shell command in the session workspace directory. "
                "Network access and destructive commands require explicit user approval. "
                "Prefer run_python for data work."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "command": {"type": "string", "description": "Shell command line"},
                    "timeout": {"type": "number", "description": "Timeout in seconds (default 30)"},
                },
                "required": ["command"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "save_artifact",
            "description": (
                "Save a named, human-readable text/table artifact (e.g. a results table, "
                "a summary, a data CSV) with full provenance."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Short artifact name"},
                    "description": {"type": "string", "description": "What this artifact is"},
                    "content": {"type": "string", "description": "Text/CSV/JSON content"},
                    "kind": {"type": "string", "description": "table|text|data", "default": "text"},
                },
                "required": ["name", "description", "content"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "list_kernel_variables",
            "description": "List variables currently held in the persistent Python kernel.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
]


def get_tool_schemas() -> list[dict]:
    return json.loads(json.dumps(TOOL_SCHEMAS))


async def _run_python(ctx: ToolContext, code: str) -> str:
    env = await ctx.kernels.get_env()
    resp = await ctx.kernels.python.run_code(code)
    parts = []
    if resp.get("output"):
        parts.append(resp["output"].rstrip())
    if resp.get("error"):
        parts.append(f"[error] {resp['error']}")
    artifact_ids = []
    for i, fig in enumerate(resp.get("figures") or [], start=1):
        data = base64.b64decode(fig)
        art = Artifact(kind="figure", name=f"figure-{i}",
                       description="Matplotlib figure generated by kernel code",
                       code=code, env=env, message_id="")
        ctx.artifacts.add_artifact(art, data=data, data_type="png")
        artifact_ids.append(art.id)
    if artifact_ids:
        parts.append("Figures generated (artifacts): " + ", ".join(artifact_ids))
        if ctx.emit:
            for aid in artifact_ids:
                art = ctx.artifacts.get(aid)
                if art:
                    await ctx.emit("artifact", {"artifact": art.to_dict()})
    if resp.get("variables"):
        parts.append("Kernel variables: " + json.dumps(resp["variables"]))
    if not parts:
        parts.append("(no output)")
    return "\n".join(parts)


async def _run_r(ctx: ToolContext, code: str) -> str:
    from ..kernels.r_kernel import RUnavailableError
    try:
        resp = await ctx.kernels.r.run_code(code)
    except RUnavailableError as e:
        return f"[error] {e}"
    parts = []
    if resp.get("output"):
        parts.append(resp["output"].rstrip())
    if resp.get("error"):
        parts.append(f"[error] {resp['error']}")
    if not parts:
        parts.append("(no output)")
    return "\n".join(parts)


async def _run_shell(ctx: ToolContext, command: str, timeout: float = 30.0) -> str:
    decision = ctx.permissions.check("run_shell", command)
    if decision == "deny":
        return "[denied] This command is blocked by the permission policy."
    if decision == "ask":
        if ctx.approval is None:
            return "[denied] This command requires approval but no approval channel is available."
        ok = await ctx.approval.request("run_shell", command,
                                        "Shell command requires approval")
        if not ok:
            return "[denied by user]"
        ctx.permissions.record("run_shell", command, "allow")
    proc = await asyncio.create_subprocess_exec(
        *command.split(),
        cwd=str(ctx.kernels.session_dir),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        out, err = await asyncio.wait_for(proc.communicate(), timeout)
    except asyncio.TimeoutError:
        proc.kill()
        return "[error] shell command timed out"
    text = out.decode(errors="replace")
    if err:
        text += ("\n[stderr]\n" + err.decode(errors="replace"))
    return text[:50_000] if text else "(no output)"


async def _save_artifact(ctx: ToolContext, name: str, description: str,
                         content: str, kind: str = "text") -> str:
    env = await ctx.kernels.get_env()
    art = Artifact(kind=kind, name=name, description=description,
                   code="# saved manually", env=env, message_id="")
    ctx.artifacts.add_artifact(art, data=content.encode(), data_type="text")
    if ctx.emit:
        await ctx.emit("artifact", {"artifact": art.to_dict()})
    return f"Saved artifact {art.id} ({kind}: {name})"


async def _list_vars(ctx: ToolContext) -> str:
    vars_ = await ctx.kernels.python.list_variables()
    return json.dumps(vars_, indent=2) if vars_ else "(kernel has no user variables)"


def build_tools(ctx: ToolContext) -> dict[str, ToolFn]:
    return {
        "run_python": lambda code: _run_python(ctx, code),
        "run_r": lambda code: _run_r(ctx, code),
        "run_shell": lambda command, timeout=30: _run_shell(ctx, command, timeout),
        "save_artifact": lambda name, description, content, kind="text":
            _save_artifact(ctx, name, description, content, kind),
        "list_kernel_variables": lambda: _list_vars(ctx),
    }
