"""Research Workbench: domain-scoped autoresearch loops over the knowledge graph.

Each *scenario* is a research domain (arXiv topics + a lens). A scenario loop
chains the pieces that the vendored app and the workbench already provide:

    Phase 1  Build corpus   pool topics -> arXiv search -> import papers into
                            the knowledge graph
    Phase 2  Synthesize     autorefine a domain research report, scored by an
                            LLM reviewer (metric: report_score, higher better) —
                            the research analog of the experiment.py loop
    Phase 3  Experiments    pick the strongest corpus papers, turn their
                            extracted experiment specs into runnable
                            experiment.py files, then run a bounded improve loop
                            (metric keep/revert), the classic autoresearch loop
    Phase 4  Fold back      re-run synthesis with the replication results so the
                            final report reflects the experiments

State lives under <data_root>/scenarios/<scenario_id>/:

    scenario.json   config + corpus + loop results (persisted)
    report.md       best domain report so far
    log.md          append-only research log
    experiments/    per-paper experiment.py + results.md
    project/        ProjectStore DB recording loop runs (workbench data model)

The two sample scenarios shipped with the tool:

    autonomous-agents-security   Autonomous Agents & Security Lapses
    enterprise-ai-security       Enterprise AI Adoption & Security Lapses

Long-running loop endpoints are submitted through the router's job registry, so
the dashboard polls jobs instead of holding a fetch open.
"""

from __future__ import annotations

import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

PHASE_LABELS = {
    "idle": "Idle",
    "building": "Building corpus",
    "synthesizing": "Synthesizing report",
    "experimenting": "Running replication experiments",
    "updating": "Folding results into report",
    "done": "Done",
    "error": "Error",
    "interrupted": "Interrupted (restart)",
}

SAMPLE_SCENARIOS = [
    {
        "id": "autonomous-agents-security",
        "name": "Autonomous Agents & Security Lapses",
        "icon": "agent",
        "description": (
            "Security failures, jailbreaks, prompt-injection and safety lapses "
            "of autonomous / LLM agents. Tracks how agents are broken, why they "
            "leak or misbehave, and what defenses exist."
        ),
        "lens": "security lapses and vulnerabilities of autonomous agents",
        "topics": [
            {"name": "Agents-Security: LLM agent security", "query": "large language model agent security"},
            {"name": "Agents-Security: agent jailbreak", "query": "LLM agent jailbreak attacks"},
            {"name": "Agents-Security: prompt injection", "query": "prompt injection autonomous agents"},
            {"name": "Agents-Security: tool-use risks", "query": "tool use language model agent vulnerabilities"},
            {"name": "Agents-Security: agent safety", "query": "AI agent safety failure cases"},
        ],
        "loop": {
            "import_top": 5,
            "max_iters": 5,
            "per_iter_budget": 45,
            "top_experiments": 2,
            "review_target": 75,
        },
    },
    {
        "id": "enterprise-ai-security",
        "name": "Enterprise AI Adoption & Security Lapses",
        "icon": "enterprise",
        "description": (
            "How enterprises adopt AI, the security lapses that appear at "
            "deployment time, and the governance / compliance / risk practices "
            "that mitigate them."
        ),
        "lens": "AI adoption in the enterprise and the security lapses that arise in production",
        "topics": [
            {"name": "Enterprise-AI: adoption", "query": "enterprise AI adoption challenges"},
            {"name": "Enterprise-AI: governance", "query": "AI governance enterprise"},
            {"name": "Enterprise-AI: security compliance", "query": "AI security compliance enterprise"},
            {"name": "Enterprise-AI: deployment risks", "query": "large language model deployment risks organization"},
        ],
        "loop": {
            "import_top": 5,
            "max_iters": 5,
            "per_iter_budget": 45,
            "top_experiments": 2,
            "review_target": 75,
        },
    },
]

REPORT_SECTIONS = (
    "# {name} — Research Knowledge Map",
    "",
    "> Autonomous research report generated by the Research Workbench over a "
    "knowledge graph of arXiv papers. Lens: {lens}.",
    "",
    "## Executive summary",
    "",
    "## Key findings",
    "",
    "## Security lapses & risks catalog",
    "",
    "## Method taxonomy",
    "",
    "## Trends",
    "",
    "## Open problems / research gaps",
    "",
    "## References",
)

REVIEW_RUBRIC = (
    "Score the report 0-100 on: coverage of the corpus, accuracy / grounding "
    "in the cited papers, structure, and the quality of insight it adds beyond "
    "a naive summary."
)


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


class ResearchWorkbench:
    """Owns scenario persistence + the chained autoresearch loop phases."""

    # In-memory live progress per scenario (fast polling for the dashboard).
    _live: dict[str, dict[str, Any]] = {}

    def __init__(self, org) -> None:
        self.org = org
        self.config = org.config
        self.pool = org.pool
        self.kg = org.kg
        self.llm = org.llm
        self._dir = Path(self.config.root_dir) / "scenarios"
        self._dir.mkdir(parents=True, exist_ok=True)
        self._seed()
        self._restore_live()

    # ------------------------------------------------------------ helpers ----

    @property
    def _store_dir(self) -> Path:
        return self._dir

    def _scenario_path(self, sid: str) -> Path:
        return self._store_dir / sid / "scenario.json"

    def _report_path(self, sid: str) -> Path:
        return self._store_dir / sid / "report.md"

    def _log_path(self, sid: str) -> Path:
        return self._store_dir / sid / "log.md"

    def _experiments_dir(self, sid: str) -> Path:
        return self._store_dir / sid / "experiments"

    def _project_dir(self, sid: str) -> Path:
        return self._store_dir / sid / "project"

    def _seed(self) -> None:
        """Create scenario.json for each sample scenario + pool topics once."""
        topics = {t["name"] for t in self.pool.get_topics()}
        for sc in SAMPLE_SCENARIOS:
            path = self._scenario_path(sc["id"])
            if not path.exists():
                path.parent.mkdir(parents=True, exist_ok=True)
                self._save(sc)
            for t in sc["topics"]:
                if t["name"] not in topics:
                    try:
                        self.pool.add_topic(t["name"], t["query"])
                    except Exception as exc:  # noqa: BLE001
                        logger.warning("seed topic %s failed: %s", t["name"], exc)

    def _save(self, sc: dict[str, Any]) -> None:
        path = self._scenario_path(sc["id"])
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(sc, indent=2, default=str))
        tmp.replace(path)

    def _status(self, sid: str) -> dict[str, Any]:
        return self._live.setdefault(sid, {
            "phase": "idle", "phase_label": PHASE_LABELS["idle"],
            "progress": 0.0, "message": "", "log": [], "error": None,
            "started_at": None, "finished_at": None,
        })

    def _set(self, sid: str, phase: str, progress: float | None = None,
             message: str | None = None) -> None:
        st = self._status(sid)
        st["phase"] = phase
        st["phase_label"] = PHASE_LABELS.get(phase, phase)
        if progress is not None:
            st["progress"] = round(progress, 4)
        if message:
            st["message"] = message
        if phase in ("done", "error"):
            st["finished_at"] = time.time()
            if phase == "error":
                st["error"] = message
        logger.info("scenario %s phase=%s: %s", sid, phase, message or "")
        self._persist_live(sid)

    def _log(self, sid: str, level: str, msg: str) -> None:
        st = self._status(sid)
        st["log"].append({"t": time.time(), "level": level, "msg": msg})
        st["log"] = st["log"][-100:]
        try:
            with open(self._log_path(sid), "a") as f:
                f.write(f"- {datetime.now(timezone.utc).isoformat()} [{level}] {msg}\n")
        except OSError:
            pass

    def _reset_live(self, sid: str) -> None:
        st = self._status(sid)
        st["phase"], st["phase_label"] = "idle", PHASE_LABELS["idle"]
        st["progress"], st["message"], st["error"] = 0.0, "", None
        st["started_at"], st["finished_at"] = time.time(), None
        st["log"] = []
        self._persist_live(sid)

    # --------------------------------------------------- live state -------
    # The fast-poll dashboard state is persisted so a restart marks in-flight
    # scenarios as "interrupted" instead of silently resetting to idle while a
    # job is still (or was) running.

    def _live_path(self, sid: str) -> Path:
        return self._store_dir / sid / "status.json"

    def _persist_live(self, sid: str) -> None:
        st = self._status(sid)
        try:
            tmp = self._live_path(sid).with_suffix(".json.tmp")
            tmp.write_text(json.dumps(st, indent=2, default=str))
            tmp.replace(self._live_path(sid))
        except OSError as exc:
            logger.warning("persist live state for %s failed: %s", sid, exc)

    def _restore_live(self) -> None:
        """Reload persisted per-scenario status; phases left mid-run after a
        restart are marked ``interrupted``."""
        for path in self._dir.glob("*/status.json"):
            sid = path.parent.name
            try:
                st = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                continue
            phase = st.get("phase", "idle")
            if phase not in ("idle", "done", "error"):
                st["phase"] = "interrupted"
                st["phase_label"] = PHASE_LABELS["interrupted"]
                st["message"] = (st.get("message") or "") + " [interrupted on restart]"
                st["error"] = "interrupted by server restart"
            self._live[sid] = st

    # ---------------------------------------------------------- scenarios ----

    def list(self) -> list[dict[str, Any]]:
        out = []
        for sc in SAMPLE_SCENARIOS:
            sid = sc["id"]
            path = self._scenario_path(sid)
            if path.exists():
                data = json.loads(path.read_text(encoding="utf-8"))
            else:
                data = dict(sc)
            st = self._status(sid)
            out.append({
                "id": data["id"], "name": data["name"],
                "icon": data.get("icon", "research"), "description": data.get("description", ""),
                "lens": data.get("lens", ""), "topics": data.get("topics", []),
                "corpus": data.get("corpus", []),
                "best_score": data.get("best_score"),
                "review_target": (data.get("loop", {}) or {}).get("review_target"),
                "last_built_at": data.get("last_built_at"),
                "last_loop": data.get("last_loop"),
                "status": st,
            })
        return out

    def get(self, sid: str) -> dict[str, Any] | None:
        path = self._scenario_path(sid)
        if not path.exists():
            return None
        data = json.loads(path.read_text(encoding="utf-8"))
        st = self._status(sid)
        data["status"] = st
        return data

    def status(self, sid: str) -> dict[str, Any]:
        st = self._status(sid)
        data = self.get(sid) or {}
        return {
            "id": sid, "status": st,
            "corpus_size": len(data.get("corpus", [])),
            "best_score": data.get("best_score"),
            "report_exists": self._report_path(sid).exists(),
        }

    def report(self, sid: str) -> str:
        path = self._report_path(sid)
        try:
            return path.read_text(encoding="utf-8") if path.exists() else ""
        except OSError:
            return ""

    def paper_notes(self, paper_id: str, max_chars: int = 2000) -> dict[str, Any]:
        """Public lookup of a paper node + its vault notes for the agent bridge."""
        n = self.kg.get_paper(paper_id)
        if not n:
            return {"found": False, "id": paper_id}
        tags = [
            e.target for e in self.kg._hive.edges
            if e.source == n.id and e.relation == "related_to"
        ]
        concepts = []
        for e in self.kg._hive.edges:
            if e.source == n.id:
                t = self.kg.get_concept(e.target)
                if t:
                    concepts.append(t.label)
        return {
            "found": True, "id": n.id, "title": n.label,
            "published": n.published,
            "abstract": (n.abstract or "")[:800],
            "tags": tags[:8], "concepts": concepts[:8],
            "notes": self._notes_summary(n.id, max_chars=max_chars),
        }

    def _save_store_experiment(self, sid: str) -> int:
        """Get-or-create the scenario's experiment id in its ProjectStore."""
        from ..store import ProjectStore

        store = ProjectStore(self._project_dir(sid))
        sc = self.get(sid) or {}
        name = sc.get("name", sid)
        eid = next((e["id"] for e in store.list_experiments() if e["name"] == name), None)
        if eid is None:
            eid = store.create_experiment(
                name, sc.get("description", ""), "report_score", None, True,
                plan="Research Workbench autoresearch loop over the scenario corpus.")
        return eid

    def _record_run(self, sid: str, kind: str, label: str, metric: float | None,
                    note: str, status: str = "done") -> None:
        try:
            from ..store import ProjectStore

            store = ProjectStore(self._project_dir(sid))
            store.add_run(
                prompt=label, reply=note[:1000], status=status,
                started_at=time.time() - 1, finished_at=time.time(),
                metrics={"report_score": metric} if metric is not None else {},
                experiment_id=self._save_store_experiment(sid),
                config={"kind": kind}, label=label[:40], kind=kind,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning("record_run for %s failed: %s", sid, exc)

    # ------------------------------------------------------- corpus build ----

    def _corpus_ids(self, sid: str) -> list[str]:
        sc = self.get(sid) or {}
        return list(sc.get("corpus", []))

    def _corpus_papers(self, sid: str) -> list[Any]:
        return [n for n in self.kg.papers if n.id in self._corpus_ids(sid)]

    def build_corpus(self, sid: str, max_papers: int | None = None,
                     model: str | None = None) -> dict[str, Any]:
        """Phase 1: ensure scenario pool topics, refresh from arXiv, import the
        freshest un-imported candidates into the knowledge graph."""
        self._reset_live(sid)
        self._set(sid, "building", 0.02, "Ensuring pool topics…")
        sc = self.get(sid)
        if not sc:
            return {"status": "error", "reason": f"unknown scenario {sid}"}
        sc_topics = {t["name"] for t in sc.get("topics", [])}
        for t in sc.get("topics", []):
            try:
                self.pool.add_topic(t["name"], t["query"])
            except Exception as exc:  # noqa: BLE001
                self._log(sid, "WARN", f"topic {t['name']}: {exc}")

        self._set(sid, "building", 0.08, "Refreshing research pool from arXiv…")
        self._log(sid, "INFO", "Refreshing pool (fetching all topics from arXiv)…")
        pool_data = self.pool.refresh()
        total_topic_papers = sum(len(v) for v in pool_data.values())
        self._log(sid, "INFO", f"Pool refresh returned {total_topic_papers} papers")

        observed = self.pool.get_observed_papers()
        cands = [
            p for p in observed
            if sc_topics and sc_topics & set(p.get("topics", [])) and not p.get("imported")
        ]
        cands.sort(key=lambda p: (p.get("published", "") or ""), reverse=True)

        want = max_papers or int((sc.get("loop", {}) or {}).get("import_top", 5))
        want = max(1, min(int(want), 20))
        chosen = cands[:want]
        self._log(sid, "INFO", f"{len(cands)} un-imported candidates, importing top {len(chosen)}")

        corpus = list(sc.get("corpus", []))
        imported, skipped = [], []
        total = max(len(chosen), 1)
        for i, p in enumerate(chosen, 1):
            self._set(sid, "building", 0.08 + 0.9 * i / total,
                      f"Importing {p['arxiv_id']} ({i}/{len(chosen)})…")
            self._log(sid, "INFO", f"Importing {p['arxiv_id']} — {p.get('title', '')[:80]}")
            try:
                r = self.org.add_by_id(p["arxiv_id"], model=model)
            except Exception as exc:  # noqa: BLE001
                r = {"status": "error", "message": f"{type(exc).__name__}: {exc}"}
            if r.get("status") in ("added", "exists"):
                self.pool.mark_imported(p["arxiv_id"])
                if p["arxiv_id"] not in corpus:
                    corpus.append(p["arxiv_id"])
                imported.append({"arxiv_id": p["arxiv_id"], "title": p.get("title", ""),
                                 "status": r.get("status")})
            else:
                skipped.append({"arxiv_id": p["arxiv_id"],
                                "message": r.get("message", "?")})

        sc["corpus"] = corpus
        sc["last_built_at"] = _utcnow()
        self._save(sc)
        self._set(sid, "done", 1.0,
                  f"Corpus built: {len(imported)} imported, {len(skipped)} skipped, "
                  f"{len(corpus)} total")
        return {"status": "ok", "imported": imported, "skipped": skipped,
                "corpus_size": len(corpus)}

    # ------------------------------------------------- corpus context --------

    def _notes_summary(self, paper_id: str, max_chars: int = 500) -> str:
        n = self.kg.get_paper(paper_id)
        if not n:
            return ""
        from .pipeline import _sanitize_id

        safe = _sanitize_id(n.label) or paper_id
        note_file = Path(self.config.vault_dir) / safe / "00_notes.md"
        if not note_file.exists():
            legacy = Path(self.config.vault_dir) / f"{safe}.md"
            note_file = legacy if legacy.exists() else None
        if not note_file:
            return ""
        try:
            text = note_file.read_text(encoding="utf-8")
        except OSError:
            return ""
        marker = "## Summary"
        if marker in text:
            text = text.split(marker, 1)[1]
        text = text.split("## ", 1)[0] if marker in text else text
        return text.strip()[:max_chars]

    def _experiment_specs(self, paper_id: str) -> list[dict[str, Any]]:
        """Extract experiment specs from the paper's vault experiment files."""
        n = self.kg.get_paper(paper_id)
        if not n:
            return []
        from .pipeline import _sanitize_id

        safe = _sanitize_id(n.label) or paper_id
        exp_dir = Path(self.config.vault_dir) / safe
        specs: list[dict[str, Any]] = []
        for f in sorted(exp_dir.glob("*-00-experiment.md")) if exp_dir.exists() else []:
            try:
                text = f.read_text(encoding="utf-8")
            except OSError:
                continue
            spec: dict[str, Any] = {"source_file": str(f)}
            for key in ("goal", "methodology", "dataset", "setup", "baselines"):
                m = text.find(f"## {key.capitalize()}")
                if m < 0:
                    continue
                rest = text[m + len(key) + 3:]
                end = rest.find("\n## ")
                spec[key] = rest[:end].strip() if end >= 0 else rest.strip()
            specs.append(spec)
        return specs

    def _corpus_context(self, sid: str, include_experiments: bool = False,
                        max_chars: int = 14000) -> str:
        lines: list[str] = []
        for n in self._corpus_papers(sid):
            tags = [
                e.target for e in self.kg._hive.edges
                if e.source == n.id and e.relation == "related_to"
            ]
            concepts = []
            for e in self.kg._hive.edges:
                if e.source == n.id:
                    t = self.kg.get_concept(e.target)
                    if t:
                        concepts.append(t.label)
            block = [
                f"### {n.label}  [arXiv:{n.id}]",
                f"Abstract: {(n.abstract or '')[:500]}",
            ]
            if tags:
                block.append("Tags: " + ", ".join(tags[:8]))
            if concepts:
                block.append("Concepts: " + ", ".join(concepts[:8]))
            summ = self._notes_summary(n.id)
            if summ:
                block.append(f"Notes: {summ}")
            if include_experiments:
                specs = self._experiment_specs(n.id)
                if specs:
                    block.append("Experiment specs: " + json.dumps(specs, default=str)[:800])
            lines.append("\n".join(block))
            if len("\n\n".join(lines)) > max_chars:
                break
        return "\n\n".join(lines)

    # ------------------------------------------------- synthesis loop --------

    def _generate_report(self, sc: dict[str, Any], ctx: str, model: str | None) -> str:
        sections = "\n".join(REPORT_SECTIONS).format(
            name=sc["name"], lens=sc.get("lens", "the domain"))
        prompt = (
            f"You are an AI research analyst building a literature knowledge map.\n\n"
            f"Domain: {sc['name']}\n"
            f"Research lens: {sc.get('lens', 'the domain')}\n\n"
            f"Corpus (papers in the knowledge graph):\n{ctx}\n\n"
            "Write a comprehensive domain research report in Markdown with exactly "
            "these sections:\n\n"
            f"{sections}\n\n"
            "Ground every claim in the corpus and cite papers as [arXiv:xxxx]. "
            "Cover concrete security lapses / failures where the corpus supports them. "
            "Be specific and quantitative when possible."
        )
        try:
            return self.llm.generate(prompt, model=model or self.config.ollama_model).strip()
        except Exception as exc:  # noqa: BLE001
            logger.error("report generation failed: %s", exc)
            return ""

    def _review_report(self, sc: dict[str, Any], ctx: str, report: str,
                       model: str | None) -> float | None:
        prompt = (
            f"Domain: {sc['name']}\nLens: {sc.get('lens', 'the domain')}\n\n"
            f"Report:\n{report}\n\nCorpus:\n{ctx}\n\n"
            f"{REVIEW_RUBRIC}\n"
            'Respond with ONLY JSON: {"score": int 0-100, "feedback": ["..."], '
            '"improvements": ["..."]}'
        )
        try:
            result = self.llm.extract_structured(
                prompt, model=model or self.config.ollama_fast_model)
        except Exception as exc:  # noqa: BLE001
            logger.error("report review failed: %s", exc)
            return None
        try:
            return float(result.get("score"))
        except (TypeError, ValueError):
            return None

    def _improve_report(self, sc: dict[str, Any], ctx: str, current: str,
                        score: float | None, model: str | None) -> str:
        prompt = (
            f"Domain: {sc['name']}\nLens: {sc.get('lens', 'the domain')}\n\n"
            f"Current report (best so far, score {score if score is not None else 'unknown'}/100):\n"
            f"{current}\n\nCorpus:\n{ctx}\n\n"
            "Produce an improved, COMPLETE revised report in the same Markdown "
            "section structure. Address weaknesses, add grounding and citations "
            "[arXiv:xxxx], surface new connections between papers, and keep all "
            "existing strong content. Do not drop sections."
        )
        try:
            return self.llm.generate(prompt, model=model or self.config.ollama_model).strip()
        except Exception as exc:  # noqa: BLE001
            logger.error("report improvement failed: %s", exc)
            return ""

    def run_synthesis(self, sid: str, include_experiments: bool = False,
                      model: str | None = None) -> dict[str, Any]:
        """Phase 2 (and 4): autorefine the domain report; metric = reviewer score."""
        self._reset_live(sid)
        sc = self.get(sid)
        if not sc:
            return {"status": "error", "reason": f"unknown scenario {sid}"}
        corpus = self._corpus_papers(sid)
        if not corpus:
            self._set(sid, "error", 1.0, "No corpus papers — run 'Build corpus' first.")
            return {"status": "error", "reason": "empty corpus"}

        cfg = sc.get("loop", {})
        max_iters = max(1, min(int(cfg.get("max_iters", 5)), 10))
        phase = "updating" if include_experiments else "synthesizing"

        self._set(sid, phase, 0.03, "Gathering corpus context…")
        ctx = self._corpus_context(sid, include_experiments=include_experiments)
        self._log(sid, "INFO", f"Corpus context ready ({len(ctx)} chars, "
                               f"{len(corpus)} papers)")

        self._set(sid, phase, 0.1, "Writing initial report…")
        draft = self._generate_report(sc, ctx, model=model)
        if not draft:
            self._set(sid, "error", 1.0, "Report generation produced no output.")
            return {"status": "error", "reason": "empty report"}

        best = self._review_report(sc, ctx, draft, model=model)
        best_src = draft
        history: list[dict[str, Any]] = []
        self._log(sid, "INFO", f"Initial report score: {best}")

        for i in range(1, max_iters + 1):
            self._set(sid, phase, 0.1 + 0.85 * i / max_iters,
                      f"Iteration {i}/{max_iters}: improving report…")
            improved = self._improve_report(sc, ctx, best_src, best, model=model)
            if not improved:
                self._log(sid, "WARN", f"Iteration {i}: no report produced — skipping")
                continue
            new_score = self._review_report(sc, ctx, improved, model=model)
            keep = new_score is not None and (best is None or new_score >= best)
            history.append({
                "iteration": i, "score": new_score,
                "kept": keep, "note": improved.splitlines()[1] if len(improved.splitlines()) > 1 else "",
            })
            self._record_run(sid, "synthesis", f"synthesis iter {i}", new_score,
                             f"score={new_score} kept={keep}")
            self._log(sid, "INFO", f"Iteration {i}: score {new_score} → "
                                   f"{'kept' if keep else 'discarded'}")
            if keep:
                best, best_src = new_score, improved

        report_path = self._report_path(sid)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(best_src, encoding="utf-8")
        sc["best_score"] = best
        self._save(sc)
        self._record_run(sid, "synthesis", "synthesis summary", best,
                         f"best report_score={best} over {len(history)} iterations")
        self._set(sid, "done", 1.0, f"Synthesis complete — best report score {best}")

        return {"status": "ok", "best_score": best, "iterations": history,
                "report_path": str(report_path)}

    # ---------------------------------------------- replication experiments ----

    def _rank_papers(self, sid: str) -> list[Any]:
        corpus_ids = set(self._corpus_ids(sid))
        degree: dict[str, int] = {}
        for e in self.kg._hive.edges:
            if e.source in corpus_ids:
                degree[e.source] = degree.get(e.source, 0) + 1
            if e.target in corpus_ids:
                degree[e.target] = degree.get(e.target, 0) + 1
        now = time.time()

        def _key(n):
            deg = degree.get(n.id, 0)
            try:
                age = now - datetime.fromisoformat((n.published or "")[:10]).timestamp()
            except (ValueError, TypeError):
                age = 365 * 86400
            recency = max(0.0, 1.0 - age / (3 * 365 * 86400))
            return deg * 2.0 + recency

        return sorted(self._corpus_papers(sid), key=_key, reverse=True)

    def _generate_experiment_code(self, sc: dict[str, Any], pid: str,
                                  spec: dict[str, Any], model: str | None) -> str:
        n = self.kg.get_paper(pid)
        prompt = (
            f"Replicate or improve the following experiment from an arXiv paper.\n\n"
            f"Paper: {n.label if n else pid}\n"
            f"Abstract: {(n.abstract or '')[:400] if n else ''}\n\n"
            f"Experiment spec:\n{json.dumps(spec, default=str)}\n\n"
            "Write ONE self-contained Python file (numpy/sklearn allowed, no "
            "external downloads) that runs in under 45 seconds. It MUST print a "
            "final line:\n"
            "METRIC <metric_name>=<value>\n\n"
            "Output ONLY a fenced ```python``` code block — no prose."
        )
        from ..autoresearch import parse_code_block

        try:
            text = self.llm.generate(prompt, model=model or self.config.ollama_model)
            return parse_code_block(text) or ""
        except Exception as exc:  # noqa: BLE001
            logger.error("experiment code generation failed for %s: %s", pid, exc)
            return ""

    def _improve_experiment(self, sid: str, pid: str, exp_dir: Path,
                            initial_code: str, spec: dict[str, Any], cfg: dict[str, Any],
                            model: str | None) -> dict[str, Any]:
        from ..autoresearch import (extract_metric, parse_code_block,
                                    run_research_experiment)

        exp_file = exp_dir / "experiment.py"
        exp_file.write_text(initial_code, encoding="utf-8")
        budget = max(15, int(cfg.get("per_iter_budget", 45)))
        iters = max(1, min(int(cfg.get("experiment_iters", 3)), 6))

        base = run_research_experiment(exp_file, budget)
        best = extract_metric(base["output"])
        best_src = initial_code
        best_name = best[0] if best else None
        best_val = float(best[1]) if best else None
        self._log(sid, "INFO", f"[{pid}] baseline: {best}")

        kept_iters = 0
        for i in range(1, iters + 1):
            self._log(sid, "INFO", f"[{pid}] improve iteration {i}/{iters}")
            prompt = (
                f"You are improving a replication experiment. Current best "
                f"{best_name}={best_val if best_val is not None else 'n/a'}.\n\n"
                f"Current experiment.py:\n{exp_file.read_text()}\n\n"
                f"Experiment spec:\n{json.dumps(spec, default=str)}\n\n"
                "Propose ONE focused change and output the COMPLETE new "
                "experiment.py in a single ```python``` code block. The final "
                "line must be METRIC <name>=<value>."
            )
            try:
                new_code = parse_code_block(
                    self.llm.generate(prompt, model=model or self.config.ollama_model)) or ""
            except Exception as exc:  # noqa: BLE001
                self._log(sid, "WARN", f"[{pid}] LLM error: {exc}")
                continue
            if not new_code:
                continue
            snapshot = exp_file.read_text()
            exp_file.write_text(new_code, encoding="utf-8")
            run = run_research_experiment(exp_file, budget)
            m = extract_metric(run["output"])
            improved = False
            if m and m[0] == best_name and best_val is not None:
                try:
                    val = float(m[1])
                    improved = val > best_val
                except ValueError:
                    improved = False
            if improved:
                best_val = float(m[1])
                best_src = new_code
                kept_iters += 1
                self._log(sid, "INFO", f"[{pid}] iter {i}: {best_name}={best_val} → kept")
            else:
                exp_file.write_text(snapshot, encoding="utf-8")
                self._log(sid, "INFO", f"[{pid}] iter {i}: no improvement → reverted")

        result = {
            "paper_id": pid,
            "metric": best_name,
            "best_value": best_val,
            "iterations": iters,
            "kept_improvements": kept_iters,
            "experiment_dir": str(exp_dir),
        }
        try:
            (exp_dir / "results.md").write_text(
                f"# Replication — {pid}\n\n"
                f"- Metric: `{best_name}` = `{best_val}`\n"
                f"- Improve iterations: {iters}, kept: {kept_iters}\n\n"
                f"Spec:\n\n```json\n{json.dumps(spec, default=str, indent=2)}\n```\n",
                encoding="utf-8")
        except OSError:
            pass
        return result

    def _append_replication_note(self, pid: str, result: dict[str, Any]) -> None:
        n = self.kg.get_paper(pid)
        if not n:
            return
        from .pipeline import _sanitize_id

        safe = _sanitize_id(n.label) or pid
        note_file = Path(self.config.vault_dir) / safe / "00_notes.md"
        if not note_file.exists():
            return
        try:
            with open(note_file, "a") as f:
                f.write("\n## Replication (Research Workbench)\n\n"
                        f"- Best metric: `{result.get('metric')}` = "
                        f"`{result.get('best_value')}`\n"
                        f"- Improve iterations: {result.get('iterations')}, "
                        f"kept: {result.get('kept_improvements')}\n")
        except OSError:
            pass

    def run_experiments(self, sid: str, top_n: int | None = None,
                        model: str | None = None) -> dict[str, Any]:
        """Phase 3: replicate/improve the strongest corpus papers' experiments."""
        self._reset_live(sid)
        sc = self.get(sid)
        if not sc:
            return {"status": "error", "reason": f"unknown scenario {sid}"}
        ranked = self._rank_papers(sid)
        cfg = sc.get("loop", {})
        want = top_n or int(cfg.get("top_experiments", 2))
        chosen = ranked[:max(1, min(int(want), 5))]
        self._log(sid, "INFO", f"Ranking papers → {len(chosen)} for replication")

        results: list[dict[str, Any]] = []
        for i, n in enumerate(chosen, 1):
            specs = self._experiment_specs(n.id)
            if not specs:
                self._log(sid, "WARN", f"{n.id} has no experiment spec — skipping")
                continue
            self._set(sid, "experimenting", (i - 1) / max(len(chosen), 1),
                      f"Replicating {n.id} ({i}/{len(chosen)})…")
            self._log(sid, "INFO", f"Replicating {n.id} — {n.label[:80]}")
            code = self._generate_experiment_code(sc, n.id, specs[0], model=model)
            if not code:
                self._log(sid, "WARN", f"{n.id}: could not generate code — skipping")
                continue
            exp_dir = self._experiments_dir(sid) / (n.id.replace("/", "_"))
            exp_dir.mkdir(parents=True, exist_ok=True)
            outcome = self._improve_experiment(sid, n.id, exp_dir, code, specs[0],
                                               cfg, model=model)
            self._append_replication_note(n.id, outcome)
            self._record_run(sid, "replication", f"replicate {n.id}",
                             outcome.get("best_value"), outcome.get("metric") or "")
            results.append(outcome)

        sc["replication"] = {"results": results, "ran_at": _utcnow()}
        self._save(sc)
        self._set(sid, "done", 1.0,
                  f"Replication complete: {len(results)} experiments improved")
        return {"status": "ok", "results": results}

    # ------------------------------------------------------- full loop -------

    def run_full_loop(self, sid: str, model: str | None = None) -> dict[str, Any]:
        """Chained autoresearch: corpus → report → experiments → fold back."""
        self._reset_live(sid)
        sc = self.get(sid)
        if not sc:
            return {"status": "error", "reason": f"unknown scenario {sid}"}

        self._set(sid, "building", 0.05, "Phase 1/4: build corpus…")
        build = self.build_corpus(sid, model=model)
        if build.get("status") != "ok":
            self._set(sid, "error", 1.0, build.get("reason", "corpus build failed"))
            return build
        if not self._corpus_ids(sid):
            self._set(sid, "error", 1.0,
                      "No corpus papers found for this scenario's arXiv topics.")
            return {"status": "error", "reason": "empty corpus"}

        self._set(sid, "synthesizing", 0.2, "Phase 2/4: synthesize domain report…")
        synth = self.run_synthesis(sid, model=model)

        self._set(sid, "experimenting", 0.4, "Phase 3/4: replication experiments…")
        exp = self.run_experiments(sid, model=model)

        self._set(sid, "updating", 0.75, "Phase 4/4: fold experiment results into report…")
        update = self.run_synthesis(sid, include_experiments=True, model=model)

        loop = {
            "build": build, "synthesis": synth, "experiments": exp,
            "update": update, "finished_at": _utcnow(),
        }
        sc["last_loop"] = {
            "best_score": (synth or {}).get("best_score"),
            "experiments": len(((exp or {}).get("results")) or []),
            "imported": len(((build or {}).get("imported")) or []),
            "finished_at": loop["finished_at"],
        }
        self._save(sc)
        self._set(sid, "done", 1.0, "Full research loop complete")
        return {"status": "ok", **loop}
